#include "EpubReaderChapterSelectionActivity.h"

#include <Epub/Section.h>
#include <GfxRenderer.h>
#include <I18n.h>
#include <Logging.h>

#include "MappedInputManager.h"
#include "components/UITheme.h"
#include "fontIds.h"

int EpubReaderChapterSelectionActivity::getTotalItems() const { return epub->getTocItemsCount(); }

void EpubReaderChapterSelectionActivity::onEnter() {
  Activity::onEnter();

  if (!epub) {
    return;
  }

  selectorIndex = epub->getTocIndexForSpineIndex(currentSpineIndex);
  if (selectorIndex == -1) {
    selectorIndex = 0;
  }

  // Prebuilder is owned by the reader and is already attached -- we just retarget
  // it during this activity. Don't attach/detach here.
  requestUpdate();
}

void EpubReaderChapterSelectionActivity::onExit() { Activity::onExit(); }

void EpubReaderChapterSelectionActivity::loop() {
  const int pageItems = UITheme::getInstance().getNumberOfItemsPerPage(renderer, true, false, true, false);
  const int totalItems = getTotalItems();

  if (mappedInput.wasReleased(MappedInputManager::Button::Confirm)) {
    const auto newSpineIndex = epub->getSpineIndexForTocIndex(selectorIndex);
    if (newSpineIndex == -1) {
      ActivityResult result;
      result.isCancelled = true;
      setResult(std::move(result));
      finish();
    } else {
      // If a prebuild for the chosen spine is in flight, drain it so the
      // reader's load-on-confirm becomes a cache hit instead of a build with
      // an INDEXING popup. RenderLock blocks until the render task finishes
      // its current pass and stops firing idle-hook ticks -- without it the
      // idle hook would step the same in-flight build concurrently with our
      // drain, corrupting parser state.
      {
        RenderLock lock(*this);
        prebuilder.drainIfNeeded(newSpineIndex, renderer);
      }
      setResult(ChapterResult{newSpineIndex});
      finish();
    }
  } else if (mappedInput.wasReleased(MappedInputManager::Button::Back)) {
    ActivityResult result;
    result.isCancelled = true;
    setResult(std::move(result));
    finish();
  }

  buttonNavigator.onNextRelease([this, totalItems] {
    selectorIndex = ButtonNavigator::nextIndex(selectorIndex, totalItems);
    requestUpdate();
  });

  buttonNavigator.onPreviousRelease([this, totalItems] {
    selectorIndex = ButtonNavigator::previousIndex(selectorIndex, totalItems);
    requestUpdate();
  });

  buttonNavigator.onNextContinuous([this, totalItems, pageItems] {
    selectorIndex = ButtonNavigator::nextPageIndex(selectorIndex, totalItems, pageItems);
    requestUpdate();
  });

  buttonNavigator.onPreviousContinuous([this, totalItems, pageItems] {
    selectorIndex = ButtonNavigator::previousPageIndex(selectorIndex, totalItems, pageItems);
    requestUpdate();
  });

  maybePrebuildHoveredChapter();
}

void EpubReaderChapterSelectionActivity::maybePrebuildHoveredChapter() {
  if (!epub || buildParams.viewportWidth == 0 || buildParams.viewportHeight == 0) {
    return;
  }

  // Reset the settle timer whenever the highlight moves; the prebuilder's
  // setTargetSpine is idempotent so calling it every loop after settle is OK,
  // but we still gate on settle to avoid re-aiming the build on every keypress
  // through the list.
  if (selectorIndex != lastSelectorIndex) {
    lastSelectorIndex = selectorIndex;
    lastSelectorChangeMs = millis();
    return;
  }
  if (millis() - lastSelectorChangeMs < PREBUILD_SETTLE_MS) return;

  const int targetSpine = epub->getSpineIndexForTocIndex(selectorIndex);
  if (targetSpine == currentSpineIndex) {
    // Hovered chapter is the one the reader is already on. No work needed.
    return;
  }
  // setTargetSpine handles out-of-range, cached, and already-targeting cases.
  // The chunked build amortizes across idle ticks from refreshes generated by
  // user navigation in this activity.
  //
  // RenderLock is mandatory: this activity's loop() runs on the main task while
  // the idle hook (which calls onTick -> stepBuild on the same prebuilder) runs
  // on the render task. Without serialization, a setTargetSpine that drops the
  // in-flight Section can race the idle hook's parser callback, freeing
  // memory the render task is currently writing through.
  {
    RenderLock lock(*this);
    prebuilder.setTargetSpine(targetSpine, epub, renderer, buildParams);
  }
}

void EpubReaderChapterSelectionActivity::render(RenderLock&&) {
  renderer.clearScreen();

  auto metrics = UITheme::getInstance().getMetrics();
  Rect screen = UITheme::getInstance().getScreenSafeArea(renderer, true, false);

  GUI.drawHeader(renderer, Rect{screen.x, screen.y + metrics.topPadding, screen.width, metrics.headerHeight},
                 tr(STR_SELECT_CHAPTER));

  const int contentTop = screen.y + metrics.topPadding + metrics.headerHeight + metrics.verticalSpacing;
  const int contentHeight = screen.height - contentTop - metrics.verticalSpacing;

  const int totalItems = getTotalItems();
  GUI.drawList(renderer, Rect{screen.x, contentTop, screen.width, contentHeight}, totalItems, selectorIndex,
               [this](int index) {
                 auto item = epub->getTocItem(index);
                 std::string indent((item.level - 1) * 2, ' ');
                 return indent + item.title;
               });

  const auto labels = mappedInput.mapLabels(tr(STR_BACK), tr(STR_SELECT), tr(STR_DIR_UP), tr(STR_DIR_DOWN));
  GUI.drawButtonHints(renderer, labels.btn1, labels.btn2, labels.btn3, labels.btn4);

  renderer.displayBuffer();
}
