#include "PluginRegistry.h"

#include <Logging.h>

// Generated by scripts/gen_plugins.py at build time. Declares
//   const PluginManifest* const g_pluginRegistry[];
//   constexpr size_t g_pluginRegistryCount;
// Empty array when no plugins are present.
#include "PluginRegistry.generated.h"

namespace PluginRegistry {

const PluginManifest* const* all() { return g_pluginRegistry; }
size_t count() { return g_pluginRegistryCount; }

void forEach(void (*cb)(const PluginManifest&)) {
  if (!cb) return;
  for (size_t i = 0; i < g_pluginRegistryCount; ++i) {
    if (g_pluginRegistry[i]) cb(*g_pluginRegistry[i]);
  }
}

void onBoot() {
  for (size_t i = 0; i < g_pluginRegistryCount; ++i) {
    const PluginManifest* m = g_pluginRegistry[i];
    if (!m) continue;
    LOG_INF("PLUGIN", "boot: %s", m->id ? m->id : "?");
    if (m->onBoot) m->onBoot();
  }
}

}  // namespace PluginRegistry
