#!/usr/bin/env python3
"""
Scan plugins/*/plugin.json and generate the plugin registry header.

For every enabled plugin, this script:
  1. Reads plugin.json to learn the manifest symbol name and build flags.
  2. Appends the plugin's build_flags to the active PlatformIO environment.
  3. Writes lib/PluginCore/PluginRegistry.generated.h, declaring each manifest
     symbol as `extern` and listing them in g_pluginRegistry[].
  4. Writes .cache/plugin-i18n-dirs.txt, a newline-separated list of plugin
     i18n directories that gen_i18n.py picks up as additional translation scan
     roots.

The committed PluginRegistry.generated.h is the empty-registry default so the
tree still builds before this script has run. Re-runs are idempotent: a
fingerprint-based skip avoids rewriting the header when nothing changed
(important because rewriting it triggers a recompile cascade).

Run order in platformio.ini matters: this script must run BEFORE gen_i18n.py
so the i18n dirs list is in place when the string table is generated.

Usage (as PlatformIO pre-script):
    extra_scripts =
      pre:scripts/gen_plugins.py
      pre:scripts/gen_i18n.py

Standalone (for local testing):
    python scripts/gen_plugins.py
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path


def _project_root() -> Path:
    # PlatformIO's SConscript exec'es the script without defining __file__, so
    # fall back to the script's actual path via sys.argv[0] when needed.
    here = Path(globals().get("__file__", sys.argv[0])).resolve()
    return here.parent.parent


PROJECT_ROOT = _project_root()
PLUGINS_DIR = PROJECT_ROOT / "plugins"
REGISTRY_HEADER = PROJECT_ROOT / "lib" / "PluginCore" / "PluginRegistry.generated.h"
I18N_DIRS_FILE = PROJECT_ROOT / ".cache" / "plugin-i18n-dirs.txt"


def discover_plugins() -> list[dict]:
    """Return one record per enabled plugin, in deterministic id order."""
    if not PLUGINS_DIR.is_dir():
        return []

    plugins = []
    for entry in sorted(PLUGINS_DIR.iterdir()):
        manifest_path = entry / "plugin.json"
        if not manifest_path.is_file():
            continue
        try:
            data = json.loads(manifest_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            sys.stderr.write(f"[gen_plugins] {manifest_path}: invalid JSON ({e})\n")
            sys.exit(1)

        if not data.get("enabled", True):
            continue

        pid = data.get("id")
        symbol = data.get("manifest_symbol")
        if not pid or not symbol:
            sys.stderr.write(
                f"[gen_plugins] {manifest_path}: missing required 'id' or 'manifest_symbol'\n"
            )
            sys.exit(1)

        # Read the sibling library.json for the PlatformIO lib name; that's what
        # lib_deps needs to reference so the LDF actually links the plugin.
        lib_name = None
        lib_json = entry / "library.json"
        if lib_json.is_file():
            try:
                lib_name = json.loads(lib_json.read_text(encoding="utf-8")).get("name")
            except json.JSONDecodeError as e:
                sys.stderr.write(f"[gen_plugins] {lib_json}: invalid JSON ({e})\n")
                sys.exit(1)
        if not lib_name:
            sys.stderr.write(
                f"[gen_plugins] {entry}: library.json is missing or has no 'name'\n"
            )
            sys.exit(1)

        plugins.append(
            {
                "dir": entry,
                "id": pid,
                "symbol": symbol,
                "lib_name": lib_name,
                "build_flags": list(data.get("build_flags") or []),
                "i18n_dirs": [entry / sub for sub in (data.get("i18n") or [])],
            }
        )
    return plugins


def render_registry_header(plugins: list[dict]) -> str:
    lines = [
        "#pragma once",
        "",
        "// Auto-generated by scripts/gen_plugins.py. Do not edit by hand.",
        "",
        '#include "PluginManifest.h"',
        "",
    ]
    for p in plugins:
        lines.append(
            f'extern "C" const PluginManifest {p["symbol"]};  // {p["id"]}'
        )
    lines.append("")
    lines.append("inline const PluginManifest* const g_pluginRegistry[] = {")
    if plugins:
        for p in plugins:
            lines.append(f"    &{p['symbol']},")
    else:
        lines.append("    nullptr,")
    lines.append("};")
    lines.append("")
    if plugins:
        lines.append(
            f"inline constexpr size_t g_pluginRegistryCount = {len(plugins)};"
        )
    else:
        lines.append("inline constexpr size_t g_pluginRegistryCount = 0;")
    lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    """Avoid touching the file when content matches — saves a recompile cascade."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def write_i18n_dirs(plugins: list[dict]) -> None:
    dirs = [str(d.relative_to(PROJECT_ROOT)) for p in plugins for d in p["i18n_dirs"] if d.is_dir()]
    write_if_changed(I18N_DIRS_FILE, "\n".join(dirs) + ("\n" if dirs else ""))


# Include paths every plugin gets automatically. Plugins routinely subclass
# Activity, use MappedInputManager, push items into the shared SettingInfo
# helpers — all of which live in src/ and its subtrees that aren't on
# PlatformIO's default lib include path. Applied globally so per-plugin
# library.json files stay free of cross-tree reach-in flags.
PLUGIN_CPPPATH_SUBDIRS = (
    "src",
    "src/activities",
    "src/activities/reader",
    "src/activities/settings",
    "src/util",
)


def apply_build_flags(env, plugins: list[dict]) -> None:
    """Append each plugin's build_flags to the active PlatformIO env."""
    for p in plugins:
        for flag in p["build_flags"]:
            env.Append(BUILD_FLAGS=[flag])


def apply_plugin_includes(env, project_root: Path) -> None:
    """Put the project's src/ subtrees on every translation unit's include path
    so plugin libraries can resolve `#include "activities/Activity.h"` and
    siblings without each plugin re-declaring the same -I reach-ins."""
    for sub in PLUGIN_CPPPATH_SUBDIRS:
        env.Append(BUILD_FLAGS=[f"-I {project_root / sub}"])


def apply_lib_deps(env, plugins: list[dict]) -> None:
    """Force-add each plugin lib to lib_deps so the PlatformIO LDF links it.

    Without this, the LDF only chases `#include` chains starting from src/, and
    plugin manifests — referenced solely via `extern "C"` declarations in the
    generated registry header — fall outside that chain. The result is the
    "undefined reference to g_plugin_<id>" linker error.
    """
    config = env.GetProjectConfig()
    section = "env:" + env["PIOENV"]
    existing = config.get(section, "lib_deps", []) or []
    if isinstance(existing, str):
        existing = [s.strip() for s in existing.splitlines() if s.strip()]
    plugin_libs = [p["lib_name"] for p in plugins]
    merged = list(existing) + [name for name in plugin_libs if name not in existing]
    config.set(section, "lib_deps", merged)


def main(env=None) -> None:
    global PROJECT_ROOT, PLUGINS_DIR, REGISTRY_HEADER, I18N_DIRS_FILE
    if env is not None:
        PROJECT_ROOT = Path(env["PROJECT_DIR"])
        PLUGINS_DIR = PROJECT_ROOT / "plugins"
        REGISTRY_HEADER = PROJECT_ROOT / "lib" / "PluginCore" / "PluginRegistry.generated.h"
        I18N_DIRS_FILE = PROJECT_ROOT / ".cache" / "plugin-i18n-dirs.txt"

    plugins = discover_plugins()
    changed = write_if_changed(REGISTRY_HEADER, render_registry_header(plugins))
    write_i18n_dirs(plugins)

    summary = ", ".join(p["id"] for p in plugins) if plugins else "(none)"
    note = "regenerated" if changed else "unchanged"
    print(f"[gen_plugins] plugins: {summary}  ({note})")

    if env is not None:
        apply_plugin_includes(env, PROJECT_ROOT)
        apply_build_flags(env, plugins)
        apply_lib_deps(env, plugins)


# PlatformIO pre-script entry point.
try:
    Import("env")  # type: ignore[name-defined]
    main(env)  # type: ignore[name-defined]
except NameError:
    if __name__ == "__main__":
        main(None)
